### ISSUE TITLE
Animal Trainer doesn't cost anything?

### ISSUE THREAD

**Issue by kamronbatman** [ServUO/ServUO#4953]
Can someone verify this functionality on actual EA servers?
Did EA remove this in a recent era change?

Here is the deletion in ServUO:
- Check:
https://github.com/ServUO/ServUO/commit/63d251645b135f2c747b3a4fd43399333bee8d3b#diff-0ef960443f3b3255b846dd8431ba17d25c0d36a6a335c2cee13da387d98983f5L265
- Consumption:
https://github.com/ServUO/ServUO/commit/63d251645b135f2c747b3a4fd43399333bee8d3b#diff-0ef960443f3b3255b846dd8431ba17d25c0d36a6a335c2cee13da387d98983f5L325

**Comment by DocKnight86** [comment]
https://forum.uo.com/discussion/7111/incorrect-system-message-from-stable-master

It hasn't since LBR. Can't find the publish notes anymore but here's Misk(UO QA) also saying they plan on updating the message. 100% has not used or needed gold for decades now on production. Just a bad left over message.

Would not have been removed otherwise.

**Comment by DocKnight86** [comment]
![Screenshot_20210803-094727_DuckDuckGo](https://user-images.githubusercontent.com/65728825/128026613-e927facb-eb81-40aa-86c8-d39309114c19.jpg)
https://uo.com/wiki/ultima-online-wiki/technical/previous-publishes/2002-2/2002-publish-15-9th-january/

Publish 15 2002.
