### ISSUE TITLE
Potentially unnoticed bank exploit

### ISSUE THREAD

**Issue by bittiez** [ServUO/ServUO#5058]
I am the main developer for a custom fork of ClassicUO, and thanks to a player report it has been discovered that there is a very simple exploit of the way the server handles banking, allowing for bank access anywhere in the world for any player.

Essentially the server will send the client a close bank packet [here](https://github.com/ServUO/ServUO/blob/8b75a7bbf5984585804c771078e5ba8427d2a5c5/Server/Items/Containers.cs#L66)

It is up to the client weather to close the bank or not, now there are checks in place for the main bank container on weather the player still has access via [this bool](https://github.com/ServUO/ServUO/blob/8b75a7bbf5984585804c771078e5ba8427d2a5c5/Server/Items/Containers.cs#L18)

There are however no checks in place for child containers that the client did not close, allowing the player to access child containers that the client did not close from anywhere in the world.

I did test this, because as said this was discovered on accident, and while I have fixed it on my fork, anyone else that may discover this has an easy, free bag of sending essentially.

If you need more information let me know.

**Comment by tr1age** [comment]
```
        public override bool OnDroppedInto(Mobile from, Container target, Point3D p)
        {
            bool canDrop = base.OnDroppedInto(from, target, p);

            if (canDrop && target is BankBox && !((BankBox)target).Opened)
            {
                return false;
            }

            return canDrop;
        }
```

Solution in containers.cs

**Comment by Voxpire** [comment]
After some digging, it appears that this may not actually be an issue;

`Mobile.CanSee(Item item)` bubbles up the item parent hierarchy, which eventually checks the bank and whether it is open or not.
https://github.com/ServUO/ServUO/blob/master/Server/Mobile.cs#L8624

If this exploit were possible, it would be due to some bad custom logic in the overriding `PlayerMobile.CanSee(Item item)` method.
https://github.com/ServUO/ServUO/blob/master/Scripts/Mobiles/PlayerMobile.cs#L4951

**Comment by bittiez** [comment]
I tested this on my personal servuo test server, and have seen it work on one live shard running Servuo, if you'd like to have a private discussion I can send you the client and you can test for yourself

**Comment by Voxpire** [comment]
You are more than welcome to DM me on Discord.

**Comment by Voxpire** [comment]
We can confirm that there is no issue, just an access level oversight; 
GM+ level overrides the checks that would otherwise prevent this behaviour, which is why it appears to be a legitimate exploit.

**Comment by tr1age** [comment]
Can confirm there is a delay when swapping from GM to Player that allows you to still access the bank for a small period of time via the client while it plays catch up to know you do not have those perms, but if a player cannot ever set themselves to GM, this won't be an issue. False alarm and fell for it myself. The code above does remove that delay though so that is fun :P
