### ISSUE TITLE
[COMBAT] Can't imbue "Fey Slayer" Property

### ISSUE THREAD

**Issue by NickEU** [ServUO/ServUO#676]
According to [UO Guide](http://www.uoguide.com/Fey_Slayer) : 

> The Fey Slayer group is a Super Slayer to all Fey creatures. As of Publish 92, the Fey slayer property can be imbued by an artificer. 

Unless i'm blind we don't have that in the list of properties we can imbue.

**Comment by NickEU** [comment]
Looks like [this](https://github.com/ServUO/ServUO/blob/8e077be8b789ad7b3624412be6f0871bb829672f/Scripts/Services/Imbuing/Core/Imbuing.cs#L1379) is where the props for imbuing are defined.

**Comment by dmurphy22** [comment]
Publish 92 was only released a month or so ago, we are not that far into development yet. Thanks for reporting though!

**Comment by NickEU** [comment]
We both know the reason it took them so many years to implement this is because they just don't care...  It's a small quality of life upgrade that i'm sure is a quick fix, that will allow you to be one step closer to OSI and at the same time won't tax you too much. But then again, i could be totally wrong on this one, you know, philosophically :D

**Comment by qbradq** [comment]
Fey Slayer is already implemented and comes on some artifacts. We don't have it turned on for Spellbooks created by Scribes (I was starting to wounder why I could never craft one ;) ) and it also needs to be added to the random loot generation tables. Should be a fairly easy to implement feature. Because it is high value and low cost I am going to put this in the Hotfix milestone rather than Future Enhancements.
